---
title: "HTandon_Project4_fall2019"
author: "Harsh Tandon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install required packages and import libraries
```{r}
#install.packages("stargazer")
  #install.packages("DT")
  #install.packages("shinyWidgets")
  #install.packages("ggplot2")
  
library(ggplot2)
library(shiny)
library(corrplot)
library(tidyverse)
library(stargazer)
library(caret)
library(dplyr)
library(gridExtra)
library(shinyWidgets)
library(DT)
```

## Set Working Directory and read dataset
```{r pressure, echo=FALSE}
#set working directory
setwd("D:/1st Qtr Study Material/R/Final/HTandon/Spotify/")

#read Dataset
data = read.csv("SpotifyFeatures.csv")
```

## Data Cleaning and Wrangling
```{r}
#timeSignature is in date format, which needs to be in x/4 format
data$time_signature
levels(data$time_signature)
levels(data$time_signature) = c("0/4", "1/4", "3/4", "4/4", "5/4")
data$time_signature

#column name genre reads differently in mac and windows
#the following code changes column Genre to "genre" if it was read incorrectly
if(colnames(data)[1] != "genre") {
  colnames(data)[1] = "genre"
}

#convert attributes like mode, key and timeSignature for machine learning
levels(data$mode)
levels(data$mode) = c(1,0)
levels(data$mode)

levels(data$key)
levels(data$key) = c(1:12)
levels(data$key)

levels(data$time_signature)
levels(data$time_signature) = c(1:5)
levels(data$time_signature)

#subset only numeric features from the data to run our model
numericFeatures = data[ ,5:ncol(data)]

#convert to numeric
numericFeatures$key = as.numeric(numericFeatures$key)
numericFeatures$mode = as.numeric(numericFeatures$mode)
numericFeatures$time_signature = as.numeric(numericFeatures$time_signature)


numericFeatures = numericFeatures[,-5]
```

## Load Machine Learning Model
```{r}
#load our trained machine learning model for prediction
load("LinearRegressionModel.rda")
```

## Run the app
```{r}
#run the app
runApp("Popularity_PredictorExplorer")
```

